version: "3.8"

services:
  couchdb:
    build: .
    container_name: obsidian-livesync-coolify
    environment:
      - COUCHDB_USER=${COUCHDB_USER:-admin}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    volumes:
      - couchdb_data:/opt/couchdb/data
    ports:
      - "${COUCHDB_PORT:-5984}:5984"
    restart: unless-stopped
    labels:
      - coolify.managed=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5984/_up"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  couchdb_data:
    driver: local